### ISSUE TITLE
haoweichi.com

### ISSUE THREAD

**Issue by wout-codes** [bogachenko/fuckfuckadblock#117]
### Basic information

**Check the link:** `https://www.haoweichi.com/`
**Category:** Anti-adblock

### User environment

**Browser:** Google Chrome
**Extension or program:** AdGuard for Windows

### Additional message
Please fix.

**Comment by bogachenko** [comment]
This was fixed a week ago https://github.com/bogachenko/fuckfuckadblock/commit/529aa694f02179e886f12699ddec3f0011d64ba3

**Comment by wout-codes** [comment]
Not fixed. I still see, telling me to disable AdGuard. Maybe try writing a rule?

**Comment by bogachenko** [comment]
For what? If we are talking about [this](https://user-images.githubusercontent.com/42205627/103404644-5564ad80-4b8f-11eb-84a9-0e8fe9e75006.png) anti-adblock (well, there is simply no other), then my rule works (In addition to the desktop, I also checked it on the tablet). If you still receive such a message, then try with only one extension (and/or program), and disable all other extensions.
Clear cache and cookies and check the logger to see if the domain `pagead2.googlesyndication.com` is unblocked for `haoweichi.com`

By the way, you can read [this](https://github.com/bogachenko/fuckfuckadblock/wiki/Problematic-extensions#article-in-english-language) article, maybe you will find something useful.

**Comment by wout-codes** [comment]
@bogachenko did you try in Adguard for Windows?

**Comment by wout-codes** [comment]
Your filter blocks when I am using Adguard AdBlocker extension. It doesn't work when I am using Adguard for Windows. I reset AdGuard to default and also disabled other extensions, still no luck. I am not sure if this is a bug in AdGuard for Windows. The devs I think should look into it.

**Comment by bogachenko** [comment]
https://user-images.githubusercontent.com/8535285/103798434-d1825800-509d-11eb-993e-d5bae18a8707.mp4

**Comment by wout-codes** [comment]
Hmmm. I am not sure now. Can you tell me what to do now?

**Comment by bogachenko** [comment]
Does it work for you? `haoweichi.com#%#//scriptlet("prevent-setTimeout", "()", "5000")`

**Comment by wout-codes** [comment]
> Does it work for you? `haoweichi.com#%#//scriptlet("prevent-setTimeout", "()", "5000")`

Yes this works. But I still don't understand how the other code works for you but not for me.

**Comment by bogachenko** [comment]
The problem is somewhere at your end, I think that something is blocking the domain `pagead2.googlesyndication.com`

**Comment by wout-codes** [comment]
What can it be? I have these lists:
1. AdGuard Base Filters
2. AdGuard Mobile Ads Filter
3. Easylist
4. AdGuard Tracking Protection Filter
5. EasyPrivacy
6. AdGuard Annoyances Filter
7. AdBlock Warning Removal List
8. I don't care about cookies
9. EasyList Cookie List
10. Online Malicious URL Blocklist
11. Spam404
12. NoCoin Filter List
13. AdGuard DNS Filter
14. FFAdBlock
15. 15. uBlock Annoyances
16. uBlock Privacy 
17. Peter Lowe's Blocklist

**Comment by bogachenko** [comment]
The problem may be not only in the sheets, but also in the programs, in the equipment. Maybe you made some edits to your hosts.txt file, or your router has dns blocking. This is not my computer, but yours, you know better.

**Comment by wout-codes** [comment]
Yes, maybe surely not in Hosts.txt. Actually I am just helping your filter to be better. This website https://www.haoweichi.com/, I don't even know what is for. So this is not a big deal.
