### ISSUE TITLE
emailnator.com

### ISSUE THREAD

**Issue by gir489returns** [bogachenko/fuckfuckadblock#370]
### Basic information

**Check the link:** `https://www.emailnator.com/inbox/gianc.b.row.n1.47@gmail.com`
**Category:** Breakage
**Reported from:** USA

### User environment

**Browser:** Microsoft Edge | 107.0.1418.56 (Official build) (64-bit)
**Adblocker:**  AdGuard Browser extension Version 4.1.46
**Extensions:** Bitwarden, Tampermonkey (Only on 4chan.org), Joshi Koukousei Captcha Service (Only on 4chan.org)
**DNS:** Comcast's DNS

### Additional message
While FFA is enabled, the page sometimes loads, sometimes doesn't, and if it does load, subsequent pages will be blank pages. For example, if I can get the home page to load, and click go, the next page will be blank. Sometimes reloading the page will bring it back, sometimes it won't. Disabling FFA fixes this quirk.

CTRL+SHIFT+R on the page to make it white.

**Comment by bogachenko** [comment]
I can't reproduce it. Is this happening only in the Edge ? What about DNS if you disable it?

**Comment by gir489returns** [comment]
I'm not sure what you mean by "What about DNS if you disable it?"

**Comment by bogachenko** [comment]
Disable third-party DNS, open another browser and install only uBO there, with default settings in the extension, install the FFA sheet after the work done, try to visit the site

**Comment by gir489returns** [comment]
Sorry it's taking me so long to get back to you about this, it's mostly a low priority issue, since I just disable FFA and the site works. 

Anyway, I did your steps, I chose 8.8.8.8 as my DNS, and Google Chrome as my test bed Browser with a fresh install (portable), installed AdGuard with FFA and I get the same symptoms as I do in Edge.

Included is a video of me reproducing the issue and showing that if I disable FFA, the behaviour goes away.

https://youtu.be/DOTszStyb2A

**Comment by bogachenko** [comment]
Check @gir489returns, everything should work now.
Surprisingly, on chrome I couldn't reproduce your problem, but on firefox (with all the same settings) the problem was resurrected.

**Comment by gir489returns** [comment]
All good now.

**Comment by gir489returns** [comment]
Actually it still occurs... But it's fine, I think it's better to ignore this issue than keep trying to track it down. It's just easier for met o shut off FFA while I use the site.
